# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "963bb67c3b5a167fb4f1fa461eb77097"
name = "state-of-resonance"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
